
-- STORED PROCEDURES

CREATE PROCEDURE TEST AS SELECT * FROM EmployeeDemographics;

EXEC TEST;

CREATE PROCEDURE TEMP_EMPLOYEE
AS CREATE TABLE #TEMP_EMPLOYEE (
JOBTITLE VARCHAR(100),
EMPLOYEEPERJOB INT,
AVGAGE INT,
AVGSALARY INT
);

INSERT INTO #TEMP_EMPLOYEE 
SELECT JOBTITLE, COUNT(JOBTITLE), AVG(Age), AVG(Salary)
FROM EmployeeDemographics DEM
JOIN EmployeeSalary SAL
ON DEM.EmployeeID = SAL.EmployeeID
GROUP BY JOBTITLE;


SELECT * FROM #TEMP_EMPLOYEE ;

EXEC TEMP_EMPLOYEE ;
