
-- Temp Tables


--CREATE TEH TABLE WHICH IS A TEMPORARY ONE
CREATE TABLE #temp_Employee (
EmployeeID INT ,
JobTitle VARCHAR(100),
Salary INT 
);

 --SELECT ALL FROM THE TABLE
SELECT * FROM  #temp_Employee ;

--INSERT TO THE TEMP TABLE
INSERT INTO  #temp_Employee VALUES (
'1001', 'HR', '45000');

--INSERTING FROM A DIFFERENT TABLE TO TAKE THE VALUES FROM IT WHICH IS A FAST WAY TO DO SO, IF THE VALUES ARE THE SAME
INSERT INTO #temp_Employee 
SELECT * FROM EmployeeSalary;

--CREATING A NEW TEMP TABLE2
DROP TABLE IF EXISTS #TEMP_EMPLOYEE2
CREATE TABLE #TEMP_EMPLOYEE2 (
JobTitle VARCHAR(50),
EmployeesPerJob INT,
AvgAge INT,
AvgSalary INT 
);

--SELECTION ALL THE VALUES IN THE TEM TABLE 2
SELECT * FROM #TEMP_EMPLOYEE2;


INSERT INTO #TEMP_EMPLOYEE2
SELECT JobTitle, COUNT(JobTitle), AVG(Age), AVG(Salary)
FROM EmployeeDemographics EMP
JOIN EmployeeSalary SAL
ON EMP.EmployeeID = SAL.EmployeeID
GROUP BY JobTitle;

SELECT * FROM #TEMP_EMPLOYEE2;

